### PR TITLE
support pick from const array

### PR DESCRIPTION
**Pull request by noamokman**
Hey,
A very small fix to support passing a const array to the pick function.
I added a test case to illustrate the use case.
Thanks!

### CODE REVIEW

**Comment by sinclairzx81** [comment]
@noamokman Hi, thanks for this!

The update looks ok to me. But would it be possible to apply a similar update to the `Type.Omit()` type also? The `Type.Pick()` and `Type.Omit()` utility types are a pair so would be good to have them updated together.

**Comment by noamokman** [comment]
Sure, on it :)

**Comment by noamokman** [comment]
Done 👍🏻

**Comment by sinclairzx81** [comment]
@noamokman Hey, Awesome :)

Everything looks good to me, will merge this one through and push the updates shortly

Thanks again for the PR, this looks great! :) 
S

**Comment by sinclairzx81** [comment]
@noamokman Updates published on `0.24.47`. Nice work! :)

**Pull request merged**
