### PR TITLE
Added discriminated union

### PR DESCRIPTION
**Pull request by madshargreave**

### CODE REVIEW

**Comment by sinclairzx81** [comment]
@madshargreave Hi, thanks for this. I'm just wondering about the need to explicitly pass the discriminator property in `Type.DescriminatedUnion(...)`. TypeScript is able to descriminate the type without explicitly informing it of what property it should use to descriminate.

See below and link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAgnAC8KYQDoA8iIBWGEjAAUCWXDgBrDgBMAXFszaAMsBgYoBLqYYEGAEosSzgANx8AVwwnNBcAOUiQES9TYNlyQPlFZTgAIQ1nDD1DYzMLGStbdkcitw8vHz8RIIysuRkFJXgAVUK44p72YEVTAG0VHDyAXXbZKkjOYkU4T2VTMAJvECd8IlIAHiFMCCo4HoA+QMRQ-n44LpYILmKuCABzDa2CEG0Irmi1yswJBoLBd2ovC4TgACrRMLBUIx-tEGHA7BAMCw4OwIPAMOJgLkVscMKFgFQvtttNU7Bp1Jp-EEHjlnq8PlSfn8ohhrhCINZZBkhTI1uUbPYnEycCiYnAAIwUIFWfmC0VY8W0qUtJVgvVwVWyCFi8wSmpSgK6-Uq+5UKGw+FeITInloolwEBEtjsd5wDirYSMJBauAAIgIoYA3BQjfcTcHJYwWjKeU5FZkDbb7XB9EYTHAuA1vFwPQQkYouEiWJgSBSkdZcQB3dhwMCO2DALE4Ag1F0AjBojFYnF4uAEonwf2kuAioA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const A = Type.Object({
  kind: Type.Literal('a'),
  value: Type.Number(),
})
const B = Type.Object({
  kind: Type.Literal('b')
})

const U = Type.Union([A, B])

function test(param: Static<typeof U>) {
  // console.log(param.value)                     // fail: Property 'value' does not exist on type
  if(param.kind === 'a') console.log(param.value) // ok

}

test({ kind: 'a', value: 1 })    // ok
test({ kind: 'b' })              // ok
// test({ kind: 'a' })           // fail: Property 'value' is missing in type '{ kind: "a"; }
// test({ kind: 'b', value: 1 }) // fail: Object literal may only specify known properties, and 'value' does not exist in type 
```
Are you able to provide a use case where you would need to specify the union discriminator in this way? There may be something I'm missing here.

Thanks again
S

**Comment by madshargreave** [comment]
Hi, thanks for the quick reply :)

The discriminator is often necessary when doing any sort of runtime schema inspection such as OpenAPI code-generation. Now, it could be passed in as a custom option as well, but then we'd lose the type-safety on the discriminator.

Mads

**Comment by sinclairzx81** [comment]
@madshargreave Would it be possible to provide this information as a custom option?

```typescript
const A = Type.Object({
  kind: Type.Literal('a'),
  value: Type.Number(),
})
const B = Type.Object({
  kind: Type.Literal('b')
})

const U = Type.Union([A, B], {
   discriminator: 'kind'
})
``` 
Which produces
```javascript
const U = {
  "discriminator": "kind",
  "anyOf": [
    {
      "type": "object",
      "properties": {
        "kind": {
          "const": "a",
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": [
        "kind",
        "value"
      ]
    },
    {
      "type": "object",
      "properties": {
        "kind": {
          "const": "b",
          "type": "string"
        }
      },
      "required": [
        "kind"
      ]
    }
  ]
}
```

**Comment by madshargreave** [comment]
@sinclairzx81 Your example above specifying the discriminator as a custom option is not type-safe. 

For example, the the examples below will not report a type error even though they're both invalid.

```
const A = Type.Object({
  kind: Type.Literal('a'),
  common: Type.Object({}),
  value: Type.Number(),
})
const B = Type.Object({
  kind: Type.Literal('b'),
  common: Type.Object({}),
})

// This key does not exist on either discriminant, so it should be impossible to specify
const U = Type.Union([A, B], {
   discriminator: 'unknownfield'
})

// While this key does exist on all discriminates, it is of type TObject and not TLiteral<string>, and therefore should not pass either.
const U = Type.Union([A, B], {
   discriminator: 'common'
})
```

I believe both of the above examples illustrate a strong use-case for enforcing type-safety of the discriminator

**Comment by madshargreave** [comment]
Also note, the DiscriminatedUnion type uses `oneOf` and not, `anyOf` which I  think reflects the semantics of TS unions better as well.

**Comment by sinclairzx81** [comment]
Would composing the type through generics work? Link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgKoB2wEVOAwgK4DOMEIA8mMXS3AF84AMygc4AcgACLYFRIAbAsCgB6GOgwAjCAA8JAWABQx1argBaK9Zu279h46fPnp87kwlgBBcABeGAAmcAAiGCwkUKByREFw1LRUbpYuqWnpGXbGxsJM8rxUoeGR0VSxgQl0ADzIcBi6MBhUgfyUNNUEVKgAfN0AFHmJAFwoOIHFUSAx7FAjANYYqBDCeITEJDXdOBA8iSwjzGwc3AX8ALyIAgCUI7UIxnBwUBgwTFCFSOMRk9PQOAB0gJ2pwBgMGdEExgE2SMZhSmQRiKRFmSAFFdARwAoMMlkXj8a4TEYSHx4ABBOAXNCYf6cLQAKwwJBgfXuRkeczkgVumn+ABlgI0oD4+hICBIrlgHnASSAQHQeTS6YzmazrlL2XAAG4+JgYRUYf4AOSYIC0GCgfUlUKuxhJVDYcAAQpSULzlUyWWyOVyDfzBRaRRItBKNY9ZfKqH6PaqEOqbTD7Y6KK6wt9SuVKlQ+tTDVm+gBtMk4J0AXUlkk5zQlMNy+UScEabD6YAIwpAI3wRFIVQ0mGW8W6V0Q0rgwGELbbmP+VeCZ3nknFw6TEGx-wUEAA5pP2-8dQo9cOoTCT0YgA)

```typescript
import { Type, Static, TUnion, CustomOptions } from '@sinclair/typebox'

// -----------------------------------------------------------------------------
// Specialized Descriminated Union
// -----------------------------------------------------------------------------

function DescriminatedUnion<T extends TUnion<any>>(union: T, descriminator: keyof Static<T>, options: CustomOptions = {}): T {
  return { descriminator, ...options, ...union }
}

// -----------------------------------------------------------------------------
// Example
// -----------------------------------------------------------------------------

const A = Type.Object({
  kind: Type.Literal('a'),
  common: Type.Object({}),
  value: Type.Number(),
})
const B = Type.Object({
  kind: Type.Literal('b'),
  common: Type.Object({}),
})

const U = DescriminatedUnion(Type.Union([A, B]), 'kind')

function test(param: Static<typeof U>) {
   if(param.kind === 'a') console.log(param.value) 
}
```

With respect to `anyOf` vs `oneOf` refer to issue https://github.com/sinclairzx81/typebox/issues/37

**Comment by sinclairzx81** [comment]
Alternatively the following removes the need to wrap `TUnion`. Link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgHkCqAdsBEzs60wNLBMAmOAMIBXAM4wIIAPJhibMXAC+cAGZQpcAOQABMXxIAbAsCgB6GOgwAjCAA8tAWABQLs2bgBabz99--AYFBwSEhbh64mCTABIbAAF4Y-HAAIhhiJFCgfERJcJxs4V6hJaVl5f4uLqoiTCTyTKnpmdlMufwFTAA8yHAYdjAYAooU1LQEANoAugB8ABQETKjSqgBcKDj8zVkgOZJQ6wDWGKgQqniExCQ9nT0zMzgQclxi66ISUrINigC8iEoASnWyFuyBmiBccDgUAwMBEUEaSAAdCint9NttWkRoDhDnx+OtOrwBDhFstzkoXJTXM53MUKgzGUzPEUAKJ2AjgQwYIrMvn8sI0kgKeAAQTgfzQmCR0msACsMPU5ghIXA8QJgVYkQAZYCDKCxOZaAhaAFYVXCkAgNia6WyhVKhCA83OKEAN1iIgwtowSIAciIQNYMFA5maqQCXMKmBI4AAhCUoLX2xUwZWq9UEpPS3X6w1aayml1Qy3Wpg+mXy1PK50RqrOaOxhiJtIZHZ7JKdOYTUU4ONTHBaTOm+s1OoNOCDCRzMAEA0gdb4IikLqWTBnfIzAEQ11Q4CqGdzzlIzMSn5-Y2muCNiDcpGGCAAc0P86RHsMXu3VPrP+cQA)

```typescript
import { Type, Static, TSchema, TUnion, UnionKind, CustomOptions } from '@sinclair/typebox'

// -----------------------------------------------------------------------------
// Specialized Discriminated Union
// -----------------------------------------------------------------------------

function DiscriminatedUnion<T extends TSchema[]>(anyOf: T, descriminator: keyof Static<TUnion<T>>, options: CustomOptions = {}): TUnion<T> {
  return { ...options, descriminator, kind: UnionKind, anyOf }
}

...

const U = DiscriminatedUnion([A, B], 'kind')
```

**Comment by sinclairzx81** [comment]
@madshargreave Hi, I'm going to close off this PR. I think the two generics based examples above are the way to go. 

The primary reason for not going with the `Type.DiscriminatedUnion(...)` type is that TypeScript doesn't need the user to specify the discriminator property in order to narrow types (due to its structural type system), as well as the descriminator property (which has been defined as a `Symbol` in this PR) being unknown to the JSON schema specification (requiring an additional third AJV `.addKeyword(...)` for such a specialized type)

With reference to getting type safety on the `descriminator` property key, this can be made type safe through the use of `keyof` (as per generics examples) and so can be implemented external to TypeBox. Many Open API users currently do something similar to support `nullable` and `string enum` types in TypeBox.

Thanks for the PR tho. If you run into any issues using the generics example, feel free to post up an issue.

Cheers
S

**Pull request closed without merging**
