### PR TITLE
Let Composition types to rely on variadic tuple types

### LINKED ISSUE #13: Union of unions
Hi, it it possible to create a union of unions?

I tried doing the following

```ts
Type.Union([
  Type.Union([ ... ]),
  Type.Union([ ... ])
]);
```

but the static type is `any`.

My use case is a large union that I would like to break up into smaller unions. I suppose that increase the union size from 8 can also work but I'd rather compose the smaller unions.

### PR DESCRIPTION
**Pull request by mooyoul**
Closes #13 

## Important Note

This PR changes minimum TypeScript version to v4 - which is potentially breaking change.

### CODE REVIEW

**Comment by sinclairzx81** [comment]
Wow, thank you!

This had been on my list of things to do for a while, so this PR is very much appreciated. The significant reduction of code leveraging variadics is absolutely wonderful. Happy to roll this PR through with the major revision to 4 (aligning with current revisions of the TypeScript compiler).

Many thanks!

**Comment by matomesc** [comment]
@sinclairzx81 can you release a new version with this PR?

**Comment by sinclairzx81** [comment]
@matomesc Hi mate, sorry yes, will be releasing this shortly, I did want to make a couple of updates before pushing this out to npm, but my current bandwidth to spend has been somewhat limited at present. Apologies there.

Will push out a minor revision update out to npm today.

**Comment by sinclairzx81** [comment]
@matomesc Have pushed an update for `0.11.0` with latest changes.

**Comment by matomesc** [comment]
Thanks!

**Pull request merged**
