### PR TITLE
adds ecosystem chapter and ts2typebox

### PR DESCRIPTION
**Pull request by xddq**
This PR would add the first ecosystem tool to the typebox docu : ]

### CODE REVIEW

**Comment by sinclairzx81** [comment]
@xddq Hi, thanks for the PR.

Happy to include this, but it would be good to gather a few other community libraries making use of TypeBox (I've been meaning to do this, but never settled on a way to best present these in the readme). I'm open to ideas so will list the thinking below.

### Initial Set of Community Packages.

So, quick search on NPM yields the following. I don't know if the authors of these projects want to be listed on the TypeBox project (or whether or not its polite to just list them). I think `ts2typebox` and `fetch-typebox` are pretty safe bets (as one is yours and the other has been mentioned in Discussion threads on the repo) but for larger frameworks using TB, I'm not sure.

- https://github.com/xddq/ts2typebox
- https://github.com/erfanium/fetch-typebox
- https://elysiajs.com/
- https://github.com/feathersjs/feathers
- https://github.com/fastify/fastify-type-provider-typebox
- https://www.npmjs.com/package/nestjs-typebox
- https://github.com/azurystudio/cheetah
- https://www.npmjs.com/package/@hookform/resolvers
- https://www.npmjs.com/package/mysql-typebox
- https://www.npmjs.com/package/h3-typebox

For ecosystem libraries, it might be worth setting up separate readme section. Ideally I'd want to be accommodating of other contributors adding their libraries there via PR. I think a markdown table might be good, with `name+link`, `description` with the description length rule being "no lines can wrap in the description cell". Packages should be ordered alphabetically as avoid TypeBox having a perceived preference on one community package over another.

Something like the following

### Ecosystem

The following are a list of community libraries 

| Package| Description |
| ---         | ---                 |
| [package A](http://github.com) | A short package description |
| [package B](http://github.com)  | A short package description |
| [package C](http://github.com)  | A short package description |
| [package D](http://github.com)  | A short package description |
| [package E](http://github.com)  | A short package description |
| [package F](http://github.com)  | A short package description |

Something like this should work quite well and establish a convention for additional packages, but open to thoughts!

**Comment by xddq** [comment]
@sinclairzx81  Hey!

Sounds reasonable. I don't know which quota of projects you would want until adding the ecosystem section.

For now, I did prepare a small dummy image asking for consent:

```
Hey!

This is a generic message asking you if you would like that this package should be mentioned in the future/new "Ecosystem" section inside the typebox repository.

Would be great if you (any maintainer) could simply drop a reponse in https://github.com/sinclairzx81/typebox/pull/435.

Want it to be part of the documentation?

    Yes -> Then please comment with the package name and a short description for it, for more info see the issue.
    No -> Please simply comment "no thanks - packageNameHere"

Sorry for posting an "issue" for this, I hope it did not bother to much, feel free to close it!
```

as well as creating an issue with this very message inside the repos for the first 5 repos you mentioned (top from bottom), perhaps you or someone else could create issues for the other repos. Let's see if this approach works?

**Comment by SaltyAom** [comment]
Hi, I'm a maintainer of [ElysiaJS](https://github.com/elysiajs/elysia), thanks to an invitation from [Elysia#45](https://github.com/elysiajs/elysia/issues/45) to this thread.

I appreciate that Elysia could be listed in Typebox's ecosystem chapter, for my end I would describe Elysia as:

> Elysia - Fast and friendly Bun web framework.

Thank you for the invitation and looking forward to the future of Type box.

**Comment by erfanium** [comment]
Hi everyone!
I would like [fetch-typebox](https://github.com/erfanium/fetch-typebox) to be also listed here. 

I guess the following description is good enough. (fell free to suggest different ones)
```
fetch-typebox - drop-in replacement for fetch that brings easy integration with TypeBox
``` 

Thank you for picking my module. i'm so happy :)

**Comment by sinclairzx81** [comment]
@xddq Hey, thank you so much for reaching out. That's amazing!

I didn't have a quota in mind, but quite happy to go out with the 3 `ts2typebox`, `fetch-typebox` and `elysiajs`. Did you want to setup the new section `Ecosystem` section with these projects listed in tabular form? 

Would be happy to merge after that (will do any last minute formatting post merge)
Thanks heaps dude!
S

**Comment by mcollina** [comment]
Yes, please include https://github.com/fastify/fastify-type-provider-typebox to the list of modules.

**Comment by xddq** [comment]
@sinclairzx81 did update based on your suggestion and the (if given) descriptions. Feel free to adapt and merge whenever :]

**Comment by sinclairzx81** [comment]
Hey, this is perfect, will merge through. 

@xddq Thanks again for reaching out to community on this, but also thank you for the community replies (@SaltyAom, @erfanium, @mcollina), that's very much appreciated :) 

Cheers!
S

**Pull request merged**
